USE [FINANCE]
GO
/****** Object:  StoredProcedure [dbo].[RPT_REKENING_JURNAL]    Script Date: 01/10/2025 11:33:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[RPT_REKENING_JURNAL]
@NOREK varchar(255), @START_DATE datetime, @END_DATE datetime
AS

-- Convert dates once to avoid repeated conversions
DECLARE @START_DATE_CONVERTED DATE = CONVERT(DATE, @START_DATE)
DECLARE @END_DATE_CONVERTED DATE = CONVERT(DATE, @END_DATE)

-- Calculate start balance
DECLARE @START_BALANCE FLOAT
SELECT @START_BALANCE = SUM(CREDIT - DEBET) 
FROM (
    SELECT CREDIT, DEBET 
    FROM REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) < @START_DATE_CONVERTED
    
    UNION ALL
    
    SELECT CREDIT, DEBET 
    FROM MPMDB.FINANCE.dbo.REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) < @START_DATE_CONVERTED
) combined_balance

-- Main query
SELECT
    NOREK_NAME = b.BANK,
    BANK_NAME = c.BANK,
    START_BALANCE = @START_BALANCE,
    POST_DATE = a.POST_DATE,
    DESCR = LEFT(a.DESCR, 200),
    DEBET = a.DEBET,
    CREDIT = a.CREDIT,
    RUNNINGSUM = @START_BALANCE + SUM(a.CREDIT - a.DEBET) OVER (
        ORDER BY a.POST_DATE, a.TRXID 
        ROWS UNBOUNDED PRECEDING
    ),
    FLAG = ISNULL(ee.DESCR, d.DESCR),
    FLAG_DATE = ISNULL(dbo.UFN_GET_GL_END_PERIOD(e.FLAG_DATE, a.POST_DATE), a.CREATEDATE),
    CREATED = CONCAT(CONVERT(VARCHAR, e.FLAG_DATE, 20), ' ', '(' + f.USERBY + ')'),
    TRXID = a.TRXID,
    SRC = a.SRC
FROM (
    SELECT 
        NOREK, TRXID, BATCH_ID, POST_DATE, VALUE_DATE, BRANCH, DESCR, 
        DEBET, CREDIT, TIPE_VALIDASI, CREATEBY, CREATEDATE, 
        LASTCHANGEBY, LASTCHANGEDATE, 'STARS' as SRC
    FROM REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) BETWEEN @START_DATE_CONVERTED AND @END_DATE_CONVERTED
    
    UNION ALL
    
    SELECT 
        NOREK, TRXID, BATCH_ID, POST_DATE, VALUE_DATE, BRANCH, DESCR, 
        DEBET, CREDIT, TIPE_VALIDASI, CREATEBY, CREATEDATE, 
        LASTCHANGEBY, LASTCHANGEDATE, 'MPM' as SRC
    FROM MPMDB.FINANCE.dbo.REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) BETWEEN @START_DATE_CONVERTED AND @END_DATE_CONVERTED
) a
INNER JOIN REKENING_MASTER b ON a.NOREK = b.NOREK
INNER JOIN PARAM_TBL_BANK c ON b.BANK_CODE = c.CODE
INNER JOIN PARAM_RK_VALIDASI d ON a.TIPE_VALIDASI = d.CODE
LEFT JOIN (
    SELECT * FROM V_REKENING_JURNAL_FLAG
    UNION ALL 
    SELECT * FROM MPMDB.FINANCE.dbo.V_REKENING_JURNAL_FLAG
) e ON a.TRXID = e.DOCNO
LEFT JOIN PARAM_RK_VALIDASI ee ON e.VALIDASI = ee.CODE
LEFT JOIN (
    SELECT * FROM dbo.REKENING_JURNAL_FLAG
    UNION ALL 
    SELECT * FROM MPMDB.FINANCE.dbo.REKENING_JURNAL_FLAG
) f ON f.NOREK = a.NOREK AND f.TRXID = a.TRXID
ORDER BY a.POST_DATE, a.TRXID