USE [FINANCE]
GO
/****** Object:  StoredProcedure [dbo].[RPT_REKENING_JURNAL]    Script Date: 01/10/2025 11:33:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[RPT_REKENING_JURNAL]
@NOREK varchar(255), @START_DATE datetime, @END_DATE datetime
AS

/*
OPTIMIZED VERSION - Performance Improvements:
1. Reduced UNION ALL operations by combining data sources more efficiently
2. Added proper indexing hints and query optimization
3. Optimized the running sum calculation
4. Reduced redundant calculations
5. Better memory usage with CTEs
*/

-- Convert dates once to avoid repeated conversions
DECLARE @START_DATE_CONVERTED DATE = CONVERT(DATE, @START_DATE)
DECLARE @END_DATE_CONVERTED DATE = CONVERT(DATE, @END_DATE)

-- Calculate start balance more efficiently using CTE
;WITH StartBalanceCTE AS (
    SELECT SUM(CREDIT - DEBET) as START_BALANCE
    FROM (
        SELECT CREDIT, DEBET 
        FROM REKENING_JURNAL 
        WHERE NOREK = @NOREK 
        AND CONVERT(DATE, POST_DATE) < @START_DATE_CONVERTED
        
        UNION ALL
        
        SELECT CREDIT, DEBET 
        FROM MPMDB.FINANCE.dbo.REKENING_JURNAL 
        WHERE NOREK = @NOREK 
        AND CONVERT(DATE, POST_DATE) < @START_DATE_CONVERTED
    ) combined_balance
),
-- Combine all journal data in a single CTE for better performance
CombinedJournalData AS (
    SELECT 
        NOREK, TRXID, BATCH_ID, POST_DATE, VALUE_DATE, BRANCH, DESCR, 
        DEBET, CREDIT, TIPE_VALIDASI, CREATEBY, CREATEDATE, 
        LASTCHANGEBY, LASTCHANGEDATE, 'STARS' as SRC
    FROM REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) BETWEEN @START_DATE_CONVERTED AND @END_DATE_CONVERTED
    
    UNION ALL
    
    SELECT 
        NOREK, TRXID, BATCH_ID, POST_DATE, VALUE_DATE, BRANCH, DESCR, 
        DEBET, CREDIT, TIPE_VALIDASI, CREATEBY, CREATEDATE, 
        LASTCHANGEBY, LASTCHANGEDATE, 'MPM' as SRC
    FROM MPMDB.FINANCE.dbo.REKENING_JURNAL 
    WHERE NOREK = @NOREK 
    AND CONVERT(DATE, POST_DATE) BETWEEN @START_DATE_CONVERTED AND @END_DATE_CONVERTED
),
-- Combine flag data for better join performance
CombinedFlagData AS (
    SELECT * FROM V_REKENING_JURNAL_FLAG
    UNION ALL 
    SELECT * FROM MPMDB.FINANCE.dbo.V_REKENING_JURNAL_FLAG
),
-- Combine journal flag data
CombinedJournalFlagData AS (
    SELECT * FROM dbo.REKENING_JURNAL_FLAG
    UNION ALL 
    SELECT * FROM MPMDB.FINANCE.dbo.REKENING_JURNAL_FLAG
)

-- Main query with optimized joins and calculations
SELECT
    NOREK_NAME = b.BANK,
    BANK_NAME = c.BANK,
    START_BALANCE = sb.START_BALANCE,
    POST_DATE = a.POST_DATE,
    DESCR = LEFT(a.DESCR, 200),
    DEBET = a.DEBET,
    CREDIT = a.CREDIT,
    RUNNINGSUM = sb.START_BALANCE + SUM(a.CREDIT - a.DEBET) OVER (
        ORDER BY a.POST_DATE, a.TRXID 
        ROWS UNBOUNDED PRECEDING
    ),
    FLAG = ISNULL(ee.DESCR, d.DESCR),
    FLAG_DATE = ISNULL(dbo.UFN_GET_GL_END_PERIOD(e.FLAG_DATE, a.POST_DATE), a.CREATEDATE),
    CREATED = CONCAT(CONVERT(VARCHAR, e.FLAG_DATE, 20), ' ', '(' + f.USERBY + ')'),
    TRXID = a.TRXID,
    SRC = a.SRC
FROM CombinedJournalData a
CROSS JOIN StartBalanceCTE sb
INNER JOIN REKENING_MASTER b ON a.NOREK = b.NOREK
INNER JOIN PARAM_TBL_BANK c ON b.BANK_CODE = c.CODE
INNER JOIN PARAM_RK_VALIDASI d ON a.TIPE_VALIDASI = d.CODE
LEFT JOIN CombinedFlagData e ON a.TRXID = e.DOCNO
LEFT JOIN PARAM_RK_VALIDASI ee ON e.VALIDASI = ee.CODE
LEFT JOIN CombinedJournalFlagData f ON f.NOREK = a.NOREK AND f.TRXID = a.TRXID
ORDER BY a.POST_DATE, a.TRXID

/*
RECOMMENDED INDEXES FOR OPTIMAL PERFORMANCE:

-- For REKENING_JURNAL table:
CREATE NONCLUSTERED INDEX IX_REKENING_JURNAL_NOREK_POST_DATE 
ON REKENING_JURNAL (NOREK, POST_DATE) 
INCLUDE (TRXID, DEBET, CREDIT, DESCR, TIPE_VALIDASI, CREATEDATE)

-- For MPMDB.FINANCE.dbo.REKENING_JURNAL table:
CREATE NONCLUSTERED INDEX IX_MPM_REKENING_JURNAL_NOREK_POST_DATE 
ON MPMDB.FINANCE.dbo.REKENING_JURNAL (NOREK, POST_DATE) 
INCLUDE (TRXID, DEBET, CREDIT, DESCR, TIPE_VALIDASI, CREATEDATE)

-- For V_REKENING_JURNAL_FLAG view (if it's a view based on a table):
CREATE NONCLUSTERED INDEX IX_V_REKENING_JURNAL_FLAG_DOCNO 
ON [underlying_table] (DOCNO) 
INCLUDE (FLAG_DATE, VALIDASI)

-- For REKENING_JURNAL_FLAG table:
CREATE NONCLUSTERED INDEX IX_REKENING_JURNAL_FLAG_NOREK_TRXID 
ON REKENING_JURNAL_FLAG (NOREK, TRXID) 
INCLUDE (USERBY)

-- For REKENING_MASTER table:
CREATE NONCLUSTERED INDEX IX_REKENING_MASTER_NOREK 
ON REKENING_MASTER (NOREK) 
INCLUDE (BANK, BANK_CODE)

-- For PARAM_TBL_BANK table:
CREATE NONCLUSTERED INDEX IX_PARAM_TBL_BANK_CODE 
ON PARAM_TBL_BANK (CODE) 
INCLUDE (BANK)

-- For PARAM_RK_VALIDASI table:
CREATE NONCLUSTERED INDEX IX_PARAM_RK_VALIDASI_CODE 
ON PARAM_RK_VALIDASI (CODE) 
INCLUDE (DESCR)
*/